"""empty message

Revision ID: 4f34c9a337ca
Revises: None
Create Date: 2020-07-24 15:04:52.900526

"""

# revision identifiers, used by Alembic.
revision = '4f34c9a337ca'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('delivery_format', sa.Enum('CSV', 'JSON', name='delivery_format_enum'), nullable=True))
    op.add_column('domains', sa.Column('delivery_protocol', sa.Enum('Mail', 'REST API', 'AMQP', name='delivery_protocol_enum'), nullable=True))
    op.add_column('domains', sa.Column('notification_interval', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'notification_interval')
    op.drop_column('domains', 'delivery_protocol')
    op.drop_column('domains', 'delivery_format')
    ### end Alembic commands ###
