"""empty message

Revision ID: 12ffc87fb64d
Revises: ea2eeea2188c
Create Date: 2017-05-08 13:16:37.031450

"""

# revision identifiers, used by Alembic.
revision = '12ffc87fb64d'
down_revision = 'ea2eeea2188c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('coc', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_memberships', 'coc')
    ### end Alembic commands ###
