"""empty message

Revision ID: 1c58a9d397a7
Revises: 12ffc87fb64d
Create Date: 2017-05-24 12:58:32.026340

"""

# revision identifiers, used by Alembic.
revision = '1c58a9d397a7'
down_revision = '12ffc87fb64d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'countries', ['cc'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    ### end Alembic commands ###
