"""empty message

Revision ID: 3d134f1aa416
Revises: 7bac2b60069d
Create Date: 2017-04-21 14:34:21.894649

"""

# revision identifiers, used by Alembic.
revision = '3d134f1aa416'
down_revision = '7bac2b60069d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('ts_deleted', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'ts_deleted')
    ### end Alembic commands ###
