"""empty message

Revision ID: 4b4e6d96c630
Revises: 92bf1a4e3e9d
Create Date: 2017-04-04 12:25:48.583500

"""

# revision identifiers, used by Alembic.
revision = '4b4e6d96c630'
down_revision = '92bf1a4e3e9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user_roles', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('organization_user_roles', sa.Column('name_german', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'organization_user_roles', ['name'])
    op.create_unique_constraint(None, 'organization_user_roles', ['name_german'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_user_roles', type_='unique')
    op.drop_constraint(None, 'organization_user_roles', type_='unique')
    op.drop_column('organization_user_roles', 'name_german')
    op.drop_column('organization_user_roles', 'deleted')
    ### end Alembic commands ###
