"""empty message

Revision ID: 563df0efdc9f
Revises: 12ffc87fb64d
Create Date: 2018-10-30 16:00:06.214947

"""

# revision identifiers, used by Alembic.
revision = '563df0efdc9f'
down_revision = '12ffc87fb64d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fodyorg_x_organization',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('ripe_org_hdl', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ripe_org_hdl')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fodyorg_x_organization')
    ### end Alembic commands ###
