"""empty message

Revision ID: 5669504eb0c4
Revises: 04537ae40768
Create Date: 2017-04-05 14:08:24.262814

"""

# revision identifiers, used by Alembic.
revision = '5669504eb0c4'
down_revision = '04537ae40768'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('membership_role_id', sa.Integer(), nullable=True))
    op.drop_constraint('organization_memberships_org_user_role_id_fkey', 'organization_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'organization_memberships', 'membership_roles', ['membership_role_id'], ['id'])
    op.drop_column('organization_memberships', 'org_user_role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('org_user_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization_memberships', type_='foreignkey')
    op.create_foreign_key('organization_memberships_org_user_role_id_fkey', 'organization_memberships', 'membership_roles', ['org_user_role_id'], ['id'])
    op.drop_column('organization_memberships', 'membership_role_id')
    ### end Alembic commands ###
