"""empty message

Revision ID: 67b7ed1a69d7
Revises: 4c4c7189593e
Create Date: 2017-04-04 12:38:53.401493

"""

# revision identifiers, used by Alembic.
revision = '67b7ed1a69d7'
down_revision = '4c4c7189593e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user_roles', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column('organization_user_roles', sa.Column('name_german', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_user_roles', 'name_german')
    op.drop_column('organization_user_roles', 'deleted')
    ### end Alembic commands ###
