"""empty message

Revision ID: 7907b0d89232
Revises: 5669504eb0c4
Create Date: 2017-04-06 09:33:27.470306

"""

# revision identifiers, used by Alembic.
revision = '7907b0d89232'
down_revision = '5669504eb0c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('city', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_memberships', 'city')
    ### end Alembic commands ###
