"""empty message

Revision ID: 7bac2b60069d
Revises: 7907b0d89232
Create Date: 2017-04-21 14:33:31.534111

"""

# revision identifiers, used by Alembic.
revision = '7bac2b60069d'
down_revision = '7907b0d89232'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ts_deleted', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ts_deleted')
    ### end Alembic commands ###
