"""empty message

Revision ID: 809b49633a03
Revises: 93119078dd31
Create Date: 2017-04-04 14:03:41.053798

"""

# revision identifiers, used by Alembic.
revision = '809b49633a03'
down_revision = '93119078dd31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user_roles', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.drop_column('organization_user_roles', 'name_display')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user_roles', sa.Column('name_display', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('organization_user_roles', 'display_name')
    ### end Alembic commands ###
