"""empty message

Revision ID: 92bf1a4e3e9d
Revises: 3247be988b6c
Create Date: 2017-04-03 14:01:21.748382

"""

# revision identifiers, used by Alembic.
revision = '92bf1a4e3e9d'
down_revision = '3247be988b6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('display_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'display_name')
    ### end Alembic commands ###
