"""empty message

Revision ID: 93119078dd31
Revises: 67b7ed1a69d7
Create Date: 2017-04-04 12:50:38.542254

"""

# revision identifiers, used by Alembic.
revision = '93119078dd31'
down_revision = '67b7ed1a69d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user_roles', sa.Column('name_display', sa.String(length=255), nullable=False))
    op.drop_column('organization_user_roles', 'name_german')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_user_roles', sa.Column('name_german', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('organization_user_roles', 'name_display')
    ### end Alembic commands ###
