"""empty message

Revision ID: c537418a55c3
Revises: 403e132911ef
Create Date: 2017-07-24 10:33:22.302426

"""

# revision identifiers, used by Alembic.
revision = 'c537418a55c3'
down_revision = '403e132911ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('sms_alerting', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_memberships', 'sms_alerting')
    ### end Alembic commands ###
