"""empty message

Revision ID: d55a3395296c
Revises: 19d023a4f56c
Create Date: 2017-03-16 15:24:42.688425

"""

# revision identifiers, used by Alembic.
revision = 'd55a3395296c'
down_revision = '19d023a4f56c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('postal_address', sa.String(length=255), nullable=True),
    sa.Column('zip', sa.String(length=25), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    ### end Alembic commands ###
