"""empty message

Revision ID: db4987b2ba9d
Revises: 1c58a9d397a7
Create Date: 2017-05-31 14:47:24.266537

"""

# revision identifiers, used by Alembic.
revision = 'db4987b2ba9d'
down_revision = '1c58a9d397a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('coc_filename', sa.String(length=255), nullable=True))
    op.add_column('organization_memberships', sa.Column('smime_filename', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('picture_filename', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture_filename')
    op.drop_column('organization_memberships', 'smime_filename')
    op.drop_column('organization_memberships', 'coc_filename')
    ### end Alembic commands ###
