"""empty message

Revision ID: e034bab4fb56
Revises: 563df0efdc9f
Create Date: 2018-11-20 14:07:11.242360

"""

# revision identifiers, used by Alembic.
revision = 'e034bab4fb56'
down_revision = '563df0efdc9f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('delivery_protocol', sa.Enum('Mail', 'REST API', 'AMQP', name='delivery_protocol_enum'), nullable=True),
    sa.Column('delivery_format', sa.Enum('CSV', 'JSON', name='delivery_format_enum'), nullable=True),
    sa.Column('notification_interval', sa.Integer(), nullable=True),
    sa.Column('ripe_org_hdl', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=255), nullable=True),
    sa.Column('cidr', postgresql.CIDR(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asn')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    ### end Alembic commands ###
